---
title: "Astro Pi: Mission Zero"
hero_image: images/banner.png
description: Bereid je voor op Mission Zero
listed: false
copyedit: true
version: 4.0.1
last_tested: 2018-06-12
steps:
  - 
    title: Inleiding
  - 
    title: Wat is een Astro Pi?
  - 
    title: Toon een bericht
  - 
    title: Voeg wat kleur toe
  - 
    title: Toon een afbeelding
  - 
    title: Meet de luchtvochtigheid
  - 
    title: Geef de luchtvochtigheid weer
  - 
    title: Verstuur je inzending
  - 
    title: 'Uitdaging: meer Astro Pi-projecten'
