---
title: 'Astro Pi: Mission Zero'
hero_image: images/MZ_banner_2024_V4.png
description: Bereid je voor op Mission Zero
listed: true
copyedit: true
version: 5.0.0
last_tested: 2018-06-12
steps:
  - title: Je gaat maken
  - title: Wat is een Astro Pi?
  - title: Toon een afbeelding
    completion:
      - engaged
  - title: Een kleur waarnemen
    completion:
      - internal
  - title: Wat kun je nog meer doen - meer Astro Pi projecten
    completion:
      - external
