---
title: 'Astro Pi: Mission Zero'
hero_image: images/astropi_mz_2024_banner.png
description: Prepare for Mission Zero
listed: true
copyedit: true
version: 5.0.0
last_tested: 2018-06-12
steps:
- title: You will make
- title: What is an Astro Pi?
- title: Display an image
  completion:
  - engaged
- title: Sense a colour
  completion:
  - internal
- title: What next — more Astro Pi projects
