---
title: "Astro Pi: Mission Zero"
hero_image: images/banner.png
description: Gjør deg klar for Mission Zero
listed: false
copyedit: true
version: 4.0.1
last_tested: 2018-06-12
steps:
  - title: Introduksjon
  - title: Hva er en Astro Pi?
  - title: Vise en melding og velge et navn for de nye Astro Pi datamaskinene
  - title: Legge til farge
  - title: Vise et bilde
  - title: Måle luftfuktigheten
  - title: Vise luftfuktigheten
  - title: Sende inn bidraget ditt
  - title: 'Utfordring: flere Astro Pi-prosjekter'
