---
title: 'Astro Pi: Mission Zero'
hero_image: images/banner.png
description: Gør klar til Mission Zero
listed: true
copyedit: true
version: 5.0.0
last_tested: 2018-06-12
steps:
  - 
    title: Du vil gøre
  - 
    title: Hvad er en Astro Pi?
  - 
    title: Vis et billede
    completion:
      - engagéret
  - 
    title: Sense en farve
    completion:
      - internal
  - 
    title: Indsend dit bidrag
