---
title: 'Astro Pi: Missão Zero'
hero_image: images/banner.png
description: Prepara-te para a Missão Zero
listed: true
copyedit: true
version: 5.0.0
last_tested: 2018-06-12
steps:
  - 
    title: Vais fazer
  - 
    title: O que é um Astro Pi?
  - 
    title: Mostrar uma imagem
    completion:
      - engaged
  - 
    title: Mostrar uma cor
    completion:
      - internal
  - 
    title: O que se segue — mais projetos Astro Pi
