---
title: "Astro Pi: Mission Zero"
hero_image: images/banner.png
description: Prepara-te para a Mission Zero
listed: false
copyedit: true
version: 4.0.1
last_tested: 2018-06-12
steps:
  - title: Introdução
  - title: O que é um Astro Pi?
  - title: Exibe uma mensagem e escolhe um nome para o novo computador do Astro Pi
  - title: Adiciona um pouco de cor
  - title: Mostrar uma imagem
  - title: Medir a humidade
  - title: Reage à humidade
  - title: Envia a tua participação
  - title: O que vem a seguir - mais projetos Astro Pi
