---
title: "Astro Pi: Mission Zero"
hero_image: images/banner.png
description: Prepara-te para a Misson Zero
listed: false
copyedit: true
version: 4.0.1
last_tested: 2018-06-12
steps:
  - 
    title: Introdução
  - 
    title: O que é um Astro Pi?
  - 
    title: Exibir uma mensagem
  - 
    title: Adiciona um pouco de cor
  - 
    title: Visualizar uma imagem
  - 
    title: Medir a humidade
  - 
    title: Exibir a humidade
  - 
    title: Envia a tua participação
  - 
    title: 'Desafio: mais projetos do Astro Pi'
