---
title: "Astro Pi: Mission Zero"
hero_image: images/banner.png
description: Prepárate para Mission Zero
listed: false
copyedit: true
version: 4.0.1
last_tested: 2018-06-12
steps:
  - 
    title: Introducción
  - 
    title: '¿Qué es un Astro Pi?'
  - 
    title: Mostrar un mensaje
  - 
    title: Añadir algo de color
  - 
    title: Mostrar una imagen
  - 
    title: Mide la humedad
  - 
    title: Muestra la humedad
  - 
    title: Enviar tu proyecto
  - 
    title: 'Desafío: Más proyectos Astro Pi'
