---
title: "Astro Pi: Mission Zero"
hero_image: images/banner.png
description: Prepárate para Mission Zero
listed: false
copyedit: true
version: 4.0.1
last_tested: 2018-06-12
steps:
  - title: Introducción
  - title: '¿Qué es un Astro Pi?'
  - title: Muestra un mensaje y elige un nombre para los nuevos ordenadores Astro Pi
  - title: Añade un poco de color
  - title: Muestra una imagen
  - title: Mide la humedad
  - title: Muestra la humedad
  - title: Envía tu proyecto
  - title: 'Desafío: Más proyectos Astro Pi'
