---
title: "Astro Pi: Mission Zero"
hero_image: images/banner.png
description: Bereite dich auf Mission Zero vor
listed: false
copyedit: true
version: 4.0.1
last_tested: 2018-06-12
steps:
  - 
    title: Einleitung
  - 
    title: Was ist ein Astro Pi?
  - 
    title: Anzeigen einer Nachricht
  - 
    title: Füge etwas Farbe hinzu
  - 
    title: Anzeigen eines Bildes
  - 
    title: Miss die Luftfeuchtigkeit
  - 
    title: Zeige die Luftfeuchtigkeit an
  - 
    title: Einreichen deines Beitrags
  - 
    title: 'Herausforderung: noch mehr Astro Pi Projekte'
