---
title: "Astro Pi: Mission Zero"
hero_image: images/banner.png
description: Pripravite se na Mission Zero
listed: false
copyedit: true
version: 4.0.1
last_tested: 2018-06-12
steps:
  - 
    title: Uvod
  - 
    title: Kaj je Astro Pi?
  - 
    title: Prikažite sporočilo
  - 
    title: Dodajte barve
  - 
    title: Prikažite sliko
  - 
    title: Izmerite vlažnost
  - 
    title: Prikažite vlažnost
  - 
    title: Pošljite svoj prispevek
  - 
    title: 'Izziv: več projektov Astro Pi'
