---
title: "Astro Pi: Mission Zero"
hero_image: images/banner.png
description: Készülj fel a Mission Zeróra!
listed: false
copyedit: true
version: 4.0.1
last_tested: 2018-06-12
steps:
  - 
    title: Bevezetés
  - 
    title: Mi az az Astro Pi?
  - 
    title: Jeleníts meg egy üzenetet!
  - 
    title: Adj hozzá egy kis színt!
  - 
    title: Jeleníts meg egy képet!
  - 
    title: Mérd meg a hőmérsékletet!
  - 
    title: Jelenítsd meg a hőmérsékletet!
  - 
    title: Küldd be a munkádat!
  - 
    title: "Kihívás: Még több Astro Pi projekt"
