---
title: "Astro Pi: Mission Zero"
hero_image: images/banner.png
description: Valmistu Mission Zeroks
listed: false
copyedit: true
version: 4.0.1
last_tested: 2018-06-12
steps:
  - 
    title: Sissejuhatus
  - 
    title: Mis on Astro Pi?
  - 
    title: Kuva sõnum
  - 
    title: Lisa värve
  - 
    title: Kuva pilt
  - 
    title: Mõõda niiskust
  - 
    title: Kuva niiskus
  - 
    title: Esita oma võistlustöö
  - 
    title: 'Väljakutse: rohkem Astro Pi projekte'
