---
title: 'Astro Pi: Mission Zero'
hero_image: images/banner.png
description: Pripravte sa na Mission Zero
listed: true
copyedit: true
version: 5.0.0
last_tested: 2018-06-12
steps:
  - 
    title: Urobíte
  - 
    title: Čo je Astro Pi?
  - 
    title: Zobraziť obrázok
    completion:
      - engaged
  - 
    title: Snímanie farby
  - 
    title: Odoslať príspevok
    completion:
      - internal
  - 
    title: Čo ďalej — ďalšie projekty Astro Pi
