---
title: 'Astro Pi: Mission Zero'
hero_image: images/MZ_banner_2024_V4.png
description: Priprav sa na Mission Zero
listed: true
copyedit: true
version: 5.0.0
last_tested: 2018-06-12
steps:
  - 
    title: Čo urobíš
  - 
    title: Čo je Astro Pi?
  - 
    title: Zobrazenie obrázka
    completion:
      - engaged
  - 
    title: Nasnímanie farby
    completion:
      - internal
  - 
    title: Čo ďalej — ďalšie projekty Astro Pi
    completion:
      - external
