---
title: "Astro Pi: Mission Zero"
hero_image: images/banner.png
description: Prépare-toi pour la Mission Zero
listed: false
copyedit: true
version: 4.0.1
last_tested: 2018-06-12
steps:
  - 
    title: Introduction
  - 
    title: Qu'est-ce qu'un Astro Pi ?
  - 
    title: Afficher un message
  - 
    title: Ajouter de la couleur
  - 
    title: Afficher une image
  - 
    title: Mesurer l'humidité
  - 
    title: Afficher l'humidité
  - 
    title: Soumettre ton programme
  - 
    title: 'Défi: d''autres projets Astro Pi'
