---
title: 'Astro Pi : Mission Zero'
hero_image: images/banner.png
description: Se préparer pour Mission Zero
listed: true
copyedit: true
version: 5.0.0
last_tested: 2018-06-12
steps:
  - 
    title: Ce que tu vas faire
  - 
    title: Qu'est-ce qu'un Astro Pi ?
  - 
    title: Afficher une image
    completion:
      - engaged
  - 
    title: Détecter une couleur
    completion:
      - internal
  - 
    title: Et ensuite — plus de projets Astro Pi
    completion:
      - external
