---
title: "Astro Pi: Mission Zero"
hero_image: images/banner.png
description: Preparati per Mission Zero
listed: false
copyedit: true
version: 4.0.1
last_tested: 2018-06-12
steps:
  - 
    title: Introduzione
  - 
    title: Che cos'è un Astro Pi?
  - 
    title: Mostra un messaggio
  - 
    title: Aggiungi un po’ di colore
  - 
    title: Mostra un’immagine
  - 
    title: Misura l'umidità
  - 
    title: Mostra l'umidità
  - 
    title: Invia il tuo programma
  - 
    title: 'Sfida: altri progetti Astro Pi'
